name: Run Web Scrapping AutoPilot Script on Schedule

# Controls when the workflow will run
on:
  schedule:
    # Runs every day at 9:00 PM UTC
    - cron: '0 16 * * *'
    
  # This allows manual triggering if needed
  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  FILEPATH: ${{ vars.FILEPATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Use the Python version you need
          cache: 'pip'

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust based on your project

      # Run the Python script
      - name: Run Python script
        shell: bash
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          CONTAINER: ${{ secrets.CONTAINER }}
          AGENT: ${{ secrets.AGENT }}
        run: |
          python soup.py "$FILEPATH" "$CONTAINER" "$AZURE_STORAGE_CONNECTION_STRING" "$AGENT"
